# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProjectCocoapodsZero' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProjectCocoapodsZero
pod 'Alamofire'
pod 'SDWebImage'
end
